# Generated by Django 4.2.16 on 2025-07-16 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_groupmessage_author_remove_groupmessage_user'),
        ('backend', '0002_course_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='groupe_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='forum.chatgroup'),
        ),
    ]
