# Generated by Django 4.2.16 on 2025-08-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_course_groupe_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groupe_chat',
        ),
    ]
