# Generated by Django 4.2.16 on 2025-08-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
