# Generated by Django 4.2.16 on 2025-07-15 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_course_forum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_alter_chatgroup_groupe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='courseGroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='body',
            field=models.TextField(),
        ),
    ]
