# Generated by Django 4.2.16 on 2025-07-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_chatgroup_coursegroup_groupmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='courseGroup',
        ),
    ]
