# Generated by Django 4.2.16 on 2025-07-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_chatgroup_coursegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='user',
        ),
    ]
