# Generated by Django 4.2.16 on 2025-08-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_course_groupe_chat'),
        ('forum', '0008_remove_groupmessage_author_remove_groupmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.DeleteModel(
            name='ChatGroup',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
